version: '3.2'

services:
    mysql-docker-container:
      image: mysql:latest
      restart: always
      environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=employee_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=user123
      volumes:
      - /Users/cfernandez/dockerVolumes/mysqlcontainer
      command: 
      - --max_connections=1024
      - --default-authentication-plugin=mysql_native_password
      ports:
        - 3306:3306
